### ISSUE TITLE
没有安装go

### ISSUE THREAD

**Issue by litongjava** [ztj1993/docker-rttys#1]
2个问题
1.rttys是基于go语言开发的,但是你并没有安装go为什么可以启动成功呢?
2.ADD指令会独占一个docker镜像层,虽然在后面的镜像层中使用rm -rf 指令删除了改文件,但是容器的大小会改变吗?

**Comment by ztj1993** [comment]
@litongjava 

1.我直接使用的二进制包，二进制包是不需要 go 环境的，编译才需要 go 环境

2.这个就未知了，但是没有 rm 的情况下，我 tmp 目录是存在文件的，so，就删除了

**Comment by ztj1993** [comment]
@litongjava 没有必要过于在乎镜像的大小，可以参考我以前的做法，使用 shell 一键脚本，将 rttys 等下载到本地，做好配置文件，然后使用一个 alpine 去启动，很多都是这样 (单机环境下)
