### ISSUE TITLE
你好，通过docker-compose部署，为什么不能自定义用户名和密码？

### ISSUE THREAD

**Issue by cdy668** [ztj1993/docker-rttys#2]
environment:
      RTTYS_USERNAME: admin
      RTTYS_PASSWORD: abc123456
      RTTYS_TOKEN: a1d4cdb1a3cd6a0e94aa3599afcddcf5

**Comment by ztj1993** [comment]
刚看到，抱歉，今天晚上我测试一下，并更新到最新版本

**Comment by ztj1993** [comment]
@cdy668 已经处理
